Нужно больше функций
htmlacademy-javascript/2276929-kekstagram-28 pull request #5
Opened 2023-02-23 08:57 UTC by AleksDamsky

Made dz

---
:mortar_board: [Нужно больше функций](https://up.htmlacademy.ru/javascript/28/user/2276929/tasks/7)

:boom: https://htmlacademy-javascript.github.io/2276929-kekstagram-28/5/

2023-02-23 19:10 UTC, PonomareVlad requested changes
В целом хорошо, но нужно ещё немного доработать решения задач 1, 2 и 4

2023-02-23 19:10 UTC, PonomareVlad commented on js/function.js
> +}
> true, если строка **меньше или равна** указанной длине

[Результаты тестов разной длины](https://javascript.htmlacademy.ponomarevlad.ru/2/1.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FAleksDamsky%2F2276929-kekstagram-28%2Fmodule2-task1%2Fjs%2Ffunction.js&func=checkStringLength)

2023-02-23 19:10 UTC, PonomareVlad commented on js/function.js
> +}
Функция должна возвращать `true` или `false`, а `undefined` — это не тоже самое что и `false` 🙂

[Результаты тестов разных строк](https://javascript.htmlacademy.ponomarevlad.ru/2/2.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FAleksDamsky%2F2276929-kekstagram-28%2Fmodule2-task1%2Fjs%2Ffunction.js&func=checkOnPalindrom)

Ваше изначальное решение мне нравится больше, только в нем не хватает приведения строки к одному регистру букв (для прохождения второго теста)

2023-02-23 19:10 UTC, PonomareVlad commented on js/function.js
> +}
Супер !

2023-02-23 19:10 UTC, PonomareVlad commented on js/function.js
> +}
Тут есть небольшая проблема с вычислением количества повторений.

[Результаты тестов с разными параметрами](https://javascript.htmlacademy.ponomarevlad.ru/2/4.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FAleksDamsky%2F2276929-kekstagram-28%2Fmodule2-task1%2Fjs%2Ffunction.js&func=getNewStr)

Попробуйте упростить (переписать по-своему) код функции, чтобы облегчить задачу.

2023-02-25 17:59 UTC, PonomareVlad requested changes
Пока не готово, нужно исправить решения двух задач

2023-02-25 17:59 UTC, PonomareVlad commented on js/function.js
>  }
> Исправил: теперь привожу **строку** к одному регистру

Приведения **одной** строки не достаточно 🙂

[Результат теста строки в разном регистре](https://javascript.htmlacademy.ponomarevlad.ru/2/2.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FAleksDamsky%2F2276929-kekstagram-28%2Fmodule2-task1%2Fjs%2Ffunction.js&func=checkOnPalindromSecond#palindrome-case)

2023-02-25 17:59 UTC, PonomareVlad commented on js/function.js
> +}
Кажется, [результаты тестов не изменились](https://javascript.htmlacademy.ponomarevlad.ru/2/4.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FAleksDamsky%2F2276929-kekstagram-28%2Fmodule2-task1%2Fjs%2Ffunction.js&func=getAnotherString) 🙂

Попробуйте переосмыслить алгоритм этой функции и написать её самостоятельно, пусть даже не так компактно, как было показано в Лайве

2023-02-25 18:40 UTC, AleksDamsky commented
Принял, сейчас буду править!

  
>Суббота, 25 февраля 2023, 20:59 +03:00 от Vladislav Ponomarev ***@***.***>:
> 
> 
>@PonomareVlad requested changes on this pull request.
>Пока не готово, нужно исправить решения двух задач
>----------------------------------------------------------------------
>In  js/function.js :
>> +function checkOnPalindromSecond(str){
>
>+  const reverceStr = str.toLowerCase().split('').reverse().join('');
>
>+  if(str !== reverceStr){
>
>+    return false;
>
>   }
>
>+  return true;
>
> }
>
>
>>Исправил: теперь привожу  строку к одному регистру
>Приведения  одной строки не достаточно 🙂
>Результат теста строки в разном регистре
>----------------------------------------------------------------------
>In  js/function.js :
>> +const getAnotherString = function(string, minLenght, stringTwo){
>
>+  const result = minLenght - string.length;
>
>+
>
>+  if(result <= 0){
>
>+    return string;
>
>+  }
>
>+
>
>+  return stringTwo.slice(0, result % stringTwo.length) + stringTwo.repeat(result / stringTwo) + string;
>
>+}
>
>
>Кажется,  результаты тестов не изменились 🙂
>Попробуйте переосмыслить алгоритм этой функции и написать её самостоятельно, пусть даже не так компактно, как было показано в Лайве
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <htmlacademy-javascript/2276929-kekstagram-28/pull/5/review/1314548117 @ github . com> 
 
 
--
Александр Хрипунов
Отправлено из Почты  Mail.ru
 

2023-03-01 18:44 UTC, merged